name: Generate, Build and Dockerize Backstage

on:
  workflow_dispatch:

jobs:
  build-backstage:
    runs-on: self-hosted

    env:
      APP_NAME: mybackstage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn Classic
        run: npm install -g yarn

      - name: Install expect (for interactive automation)
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Generate Backstage App Non-Interactively
        run: |
          expect <<EOF
          spawn npx @backstage/create-app
          expect "Enter a name for the app"
          send "$env(APP_NAME)\r"
          expect eof
          EOF

      - name: Install Dependencies
        run: yarn install --immutable
        working-directory: ${{ env.APP_NAME }}

      - name: Build Backend
        run: yarn workspace backend build
        working-directory: ${{ env.APP_NAME }}

      - name: Build Docker Image
        run: docker build -f packages/backend/Dockerfile -t backstage .
        working-directory: ${{ env.APP_NAME }}
