name: Build Backstage Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backstage:
    runs-on: self-hosted  # This uses your EC2 Ubuntu runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn Classic (v1.x)
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Backstage Backend
        run: yarn workspace backend build

      - name: Build Docker Image
        run: |
          docker build -f packages/backend/Dockerfile -t backstage .
